// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3OpIU0iiezGo89vQuiRvQmf5-BstizE4',
    appId: '1:1080828057504:web:74cb463d5e326f815af6c5',
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    authDomain: 'eventify3-7cffd.firebaseapp.com',
    storageBucket: 'eventify3-7cffd.firebasestorage.app',
    measurementId: 'G-XD0HR5MPS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBWioJCUVFt6w_owoCNMBo8s7vRhT_WQ',
    appId: '1:1080828057504:android:8d0dc08895ae42c85af6c5',
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    storageBucket: 'eventify3-7cffd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3OpIU0iiezGo89vQuiRvQmf5-BstizE4',
    appId: '1:1080828057504:web:66b72a8b09c602c45af6c5',
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    authDomain: 'eventify3-7cffd.firebaseapp.com',
    storageBucket: 'eventify3-7cffd.firebasestorage.app',
    measurementId: 'G-4V624MSM4Y',
  );
}
