// lib/firebase_options.dart
// This file is auto-generated by FlutterFire CLI.
// It is an internal file that should not be manually modified.
// However, in this specific debugging scenario, we are manually populating it
// with verified credentials from your Firebase Console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Credentials for your eventify3-7cffd project (from your web app config in screenshot)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC30pIUqieZGo89QuVRvqmf5-BstizE4',
    appId: '1:1080828057504:web:66b72a8b09c602c45af6c5',
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    authDomain: 'eventify3-7cffd.firebaseapp.com',
    // IMPORTANT: Use the .appspot.com format or your custom bucket name if explicitly intended
    // Since you successfully applied CORS to 'eventify3-7cffd-images', we'll use that here.
    storageBucket:
        'eventify3-7cffd-images', // <--- Ensure this is your chosen bucket
    measurementId: 'G-4V624MSM4Y',
  );

  // For Android, iOS, Windows, macOS, Linux:
  // Using the same project-level values. For `apiKey` and `appId`, you'd
  // typically use specific ones if you registered each platform in Firebase.
  // For this assignment, using the web ones is a common shortcut if not all
  // platforms are registered individually.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC30pIUqieZGo89QuVRvqmf5-BstizE4',
    appId:
        '1:1080828057504:android:YOUR_ANDROID_APP_ID_SUFFIX', // Replace with your actual Android app ID from Firebase Console, e.g., ...:android:XYZ123
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    storageBucket:
        'eventify3-7cffd-images', // <--- Ensure consistency with your chosen bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30pIUqieZGo89QuVRvqmf5-BstizE4',
    appId:
        '1:1080828057504:ios:YOUR_IOS_APP_ID_SUFFIX', // Replace with your actual iOS app ID from Firebase Console, e.g., ...:ios:ABC456
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    storageBucket:
        'eventify3-7cffd-images', // <--- Ensure consistency with your chosen bucket
    // bundleId: 'com.example.eventify2', // Uncomment and set your bundle ID if applicable
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC30pIUqieZGo89QuVRvqmf5-BstizE4',
    appId:
        '1:1080828057504:macos:YOUR_MACOS_APP_ID_SUFFIX', // Replace with your actual macOS app ID from Firebase Console
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    storageBucket:
        'eventify3-7cffd-images', // <--- Ensure consistency with your chosen bucket
    // bundleId: 'com.example.eventify2.macos', // Uncomment and set your bundle ID if applicable
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC30pIUqieZGo89QuVRvqmf5-BstizE4',
    appId:
        '1:1080828057504:windows:YOUR_WINDOWS_APP_ID_SUFFIX', // Replace with your actual Windows app ID from Firebase Console
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    storageBucket:
        'eventify3-7cffd-images', // <--- Ensure consistency with your chosen bucket
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC30pIUqieZGo89QuVRvqmf5-BstizE4',
    appId:
        '1:1080828057504:linux:YOUR_LINUX_APP_ID_SUFFIX', // Replace with your actual Linux app ID from Firebase Console
    messagingSenderId: '1080828057504',
    projectId: 'eventify3-7cffd',
    storageBucket:
        'eventify3-7cffd-images', // <--- Ensure consistency with your chosen bucket
  );
}
