import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Required for Firebase initialization
import 'package:eventify2/firebase_options.dart'; // Auto-generated by FlutterFire CLI - ENSURE 'eventify2'
import 'package:eventify2/pages/home_page.dart'; // Your custom Home Page - ENSURE 'eventify2'

void main() async {
  // main needs to be async because Firebase.initializeApp() is an async call
  // WidgetsFlutterBinding.ensureInitialized() is required before calling Firebase.initializeApp()
  // or any plugin-specific code that might need native bindings.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions
        .currentPlatform, // Uses the generated firebase_options.dart
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key}); // Use super.key for cleaner code

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Event Manager', // Your app's title
      debugShowCheckedModeBanner:
          false, // Hides the debug banner in release mode
      theme: ThemeData(
        primarySwatch: Colors.deepPurple, // A nice primary color for your app
        visualDensity: VisualDensity.adaptivePlatformDensity,
        // You can use a newer theme setup if you prefer, e.g.:
        // colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        // useMaterial3: true,
      ),
      home:
          const HomePage(), // <--- This sets your custom HomePage as the starting point
    );
  }
}
